# banco-docker/Dockerfile
FROM postgres:15

# Configurações iniciais do banco
ENV POSTGRES_DB=singular
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=<POSTGRES_PASSWORD>

# opcional: copiar scripts para inicialização automática
# COPY sql/*.sql /docker-entrypoint-initdb.d/
